### ISSUE TITLE
Breaks PWAs.

### ISSUE THREAD

**Issue by bobarakatx** [MarcGuiselin/wedge#5] opened 2024-01-09 19:23 UTC
PWAs don't work anymore. Whether it is installed or not, I get this error.
"Windows cannot find 'C:\Program Files (x86)\Wedge\Edge\pwahelper.exe'. Make sure you typed the name correctly, and then try again.
![image](https://github.com/MarcGuiselin/wedge/assets/98258356/a6f560d0-d6de-4320-894e-5a8a3017942c)

**Comment by MarcGuiselin** [comment] 2024-05-11 13:18
Sorry for taking a while to get back to you.

From the error code you share, it seems like an issue caused by an earlier version of Wedge that used a different technique to intercept requests to Edge (hence the custom path to Edge through Wedge's install location). This path doesn't exist anymore on Wedge 2.2.

You might have updated Wedge already, but in case you haven't, make sure to uninstall and reinstall the latest version. [latest download link](https://github.com/MarcGuiselin/wedge/releases/latest)

With PWAs you have the choice to install it from any modern web browser. I suggest you uninstall those you installed with Edge, delete the broken shortcuts to the PWA, and reinstall using your default browser.

If you still decide to use Edge for PWAs (for whatever reason), this issue should be completely fixed in Wedge 2.2. In my tests PWAs work great!

Closing for now, but please feel free to leave another comment if you continue to run into issues.

**Closed as completed by MarcGuiselin** 2024-05-11 13:18 UTC
